- hosts: localhost
  connection: local
  tasks:
    - name: Instalar software base (Pacman)
      become: yes
      community.general.pacman:
        name: 
          - kitty
          - docker
          - docker-compose
          - helix
          - zellij
          - fish
          - wl-clipboard
          - starship
          - syncthing
          - telegram-desktop
          - base-devel
          - zoxide
          - mcfly
          - neovim
          - yay
          - yazi
          - bat
          - exa
          - inkscape
          - gimp
          - mlocate
          - unzip
          - direnv
          - snapd
          - obs-studio
          - ghostty
          - niri
          - nodejs
          - npm
          
        state: present
        update_cache: yes
        
    - name: Eliminar versión estable de quickshell para evitar conflictos
      become: yes
      community.general.pacman:
        name: quickshell
        state: absent
        

    - name: Eliminar versión estable de quickshell para evitar conflictos
      become: yes
      community.general.pacman:
        name: dms-shell-git
        state: absent
               
    - name: Instalar software de comunidad (AUR)
      kewlfft.aur.aur:
        name: 
          - television
          - hplip-plugin
          - quickshell-git
          - dms-shell-git
        state: present
      become: no

    - name: Configurar docker
      become: yes
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Configurar servicios dms
      become: false
      systemd:
        name: dms.service
        enabled: yes
        state: started
        scope: user

    - name: Configurar el nombre de usuario global de git
      become: false
      community.general.git_config:
        name: user.name
        value: "Juan Manuel Schillaci"
        scope: global

    - name: Configurar el correo electronico global de git
      become: false
      community.general.git_config:
        name: user.email
        value: "jmschillaci@gmail.com"
        scope: global

    - name: Instalar ble.sh
      ansible.builtin.git:
        repo: https://github.com/akinomyoga/ble.sh.git
        dest: /tmp/src/ble.sh
        recursive: yes
        depth: 1
      register: ble_clone

    - name: Compilar e instalar ble.sh
      #command: make -C /tmp/src/ble.sh install PREFIX={{ ansible_env.HOME }}/.local
      command: make -C /tmp/src/ble.sh install PREFIX={{ ansible_facts["env"]["HOME"] }}/.local
      when: ble_clone.changed

    - name: Eliminar fuentes de ble.sh
      file:
        path: /tmp/src/ble.sh
        state: absent
      when: ble_clone.changed

    - name: Instalar OpenCode usando el script oficial de bash
      shell: "curl -fsSL https://opencode.ai/install | bash"
      args:
        chdir: "{{ ansible_facts.env.HOME }}"
        creates: "{{ ansible_facts.env.HOME }}.opencode/bin/opencode"  # Evita que se vuelva a ejecutar si ya existe

    - name: Asegurar que Fish esté instalado (ejemplo para Debian/Ubuntu)
      ansible.builtin.package:
        name: fish
        state: present

    - name: Obtener la ruta absoluta del ejecutable de Fish
      ansible.builtin.command: which fish
      register: fish_path
      changed_when: false
      failed_when: fish_path.rc != 0

    - name: Asegurar que Fish esté en la lista de shells permitidos (/etc/shells)
      ansible.builtin.lineinfile:
        path: /etc/shells
        line: "{{ fish_path.stdout }}"
        state: present

    - name: Cambiar el shell por defecto del usuario a Fish
      ansible.builtin.user:
        name: "{{ ansible_facts.user_id }}"
        shell: "{{ fish_path.stdout }}"
      become: true
